### ISSUE TITLE
Accessors

### ISSUE THREAD

**Issue by disteph** [arlencox/mlbdd#3]
Looks like a great package!
But am I missing something obvious or the API doesn't provide constant time accessors?
Typically, I'd like a function
reveal : t -> t e
and, even better, a version
reveal' : t -> t e'
where e' is a variant of e without the Not constructor.
Ideally, if the branching constructor in e' could also feature the node id, I'd have a use for that...

**Comment by arlencox** [comment]
Thanks for this suggestion.  I can definitely provide the first function.  The first function I will call `inspect`:

```
val inspect : t -> t e
```

I'm not quite sure what you mean for the second function.  Are you asking for raw access to the representation used by mlbdd in the implementation?

```
  type node =
    | NFalse
    | NIf of node (* 0 edge *)
             * var  (* variable *)
             * cnode    (* 1 edge *)
             * int  (* code always even *)
```

Then the function `internal_inspect` would be the following:

```
val internal_inspect : t -> node * bool
```
where the bool is true if the node is negated

**Comment by disteph** [comment]
Thanks for the quick reply! Great for inspect.
Sorry about the confusion, I actually meant two things:
One thing would be a variant of inspect ``val inspect' : t -> t e'``
where 
``
type 'a e' =
  | False               (** the false BDD *)
  | True                (** the true BDD *)
  | If of 'a * var * 'a (** result from false branch, variable, result from
                            true branch *)
``
In fact, they could be called type ``eb`` and function ``inspectb``, by analogy to ``to_string`` and ``to_stringb``, because they expose the top-level information displayed by the to_string functions, accessible in constant time.

Except that the two ``to_string`` functions also provide the base node id number, and I have a use for that (having unique ids can be valuable). So I'd also like to get that information, perhaps by making
inspect (resp. inspectb) return a pair t e * int (resp. t eb * int) ?
The integer being the top-level id being returned by to_string (resp. to_stringb)...

**Comment by arlencox** [comment]
I understand now.  I can do that.  I'll try to take care of it tonight.

I will add a separate function to get the unique id for a node.  I'll probably call it `id`.

**Comment by disteph** [comment]
Oh, that'd be great; thank you so much!

**Comment by arlencox** [comment]
It's not submitted to opam yet, but would you mind checking out the updates to make sure they do what you need?  If so I'll submit it to opam tomorrow night.

I added `inspect`, `inspectb`, and `id` to both the standard and the raw interfaces.

**Comment by disteph** [comment]
Hi,
yes, I've cloned and tested, it's exactly what I needed.
Thanks!

**Comment by disteph** [comment]
Actually if you haven't submitted to opam yet, would it make sense to also have a function ``foldb : ('r b -> 'r) -> t -> 'r``, for those who want to traverse the BDD but are not used to handling complement edges?

**Comment by arlencox** [comment]
This is added, tested, and checked in.  It has also been submitted to opam, though the ci is taking a long time.

**Comment by disteph** [comment]
Great, thanks!
